= UX-Konzept: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die Benutzeroberflächen des Systems *Bahnplan* beschrieben. Dies können sein:

* Personas der wichtigsten Stakeholder
* Nutzerkontext
* Wireframes relevanter Benutzeroberflächen
* Zusammenhänge mittels Taskflow-Diagrammen
* Angaben über die Gestaltung der Benutzeroberfläche, z.B. Styling, Bedienbarkeit, ...

== Personas
// Fügen Sie hier als Tabelle oder Bild die Persons der wichtigsten Stakeholder ein

=== Kunde: Prof. Iffländer
* Alter: 55
* Geschlecht: männlich
* Beruf: Professor an der HTW Dresden
* Technikaffinität: routinierter PC-Nutzer, mag detaillierte Berichte und kurze Demos; wenig Zeit für tiefegehende Tests
* Ziel: möchte einen der Vision entsprechenden MVP begutachten
* Frustrationen: unsaubere Kommunikation, fehlende Dokumentation

=== Nutzer: Eric Elseländer
* Alter: 32
* Geschlecht: männlich
* Beruf: Bürojob
* Familienstand: ledig
* Technikaffinität: programmiert hobbymäßig, sehr vertraut mit PC und Smartphone
* Vorwissen: kennt Ausschreibungssysteme und Fahrzeugtypen der Bahn sehr genau
* Ziele: komplexe, realitätsnahe Simulation mit vielen Stellschrauben; Intuitives UI
* Frustrationen: zu geringe Komplexität, bürokratische Oberflächen, schlechte Navigation, fehlendes modernes UI

=== Nutzer: Sophie Kramer
* Alter: 27
* Geschlecht: weiblich
* Beruf: Marketing-Referentin
* Familienstand: in Partnerschaft
* Technikaffinität: nutzt Smartphone täglich, Desktop weniger häufig; kein Programmier- oder Fachbahnwissen, lernt gern per Tutorial
* Vorwissen: Bahnbegeistert durch Reisen, kennt Fahrzeugtypen und Ausschreibungen nur oberflächlich
* Ziele: schnell Spielprinzip verstehen, mit wenigen Klicks eigene Gesellschaft starten
* Frustrationen: Fachbegriffe ohne Erklärung, zu viele Tabellen ohne Leitfaden, lange Einarbeitung, fehlende "Einsteiger"-Modi

=== Gesetzgeber: Anna Weber
* Alter: 45
* Geschlecht: weiblich
* Beruf: Juristin / Datenschutzbeauftragte
* Technikaffinität: nutzt Standard-Bürosoftware, erwartet klare Datenschutz- und Sicherheitsnachweise
* Ziele: DSGVO-konforme Verarbeitung, transparente Impressums- und Datenschutzhinweise, minimale Datenerhebung
* Frustrationen: fehlende Einwilligungen, unklare Datenflüsse, technische Maßnahmen ohne Dokumentation

== Nutzungskontext
// Beschreiben Sie die Arbeitsaufgaben, Arbeitsmittel, physische und soziale Umgebung, in der das Produkt genutzt wird. 
// Eventuell sind Angaben zu Fehlerquellen, Häufigkeiten von Ereignisse sowie Bearbeitungsdauern von Vorgängen relevant

//Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Wireframes und Wireflow
// Fügen Sie Wireframes als Bilder oder als Link (z.B. zu einem Miroboard) ein
// Beziehen Sie ihre Wireframes auf konkrete User Stories oder Epics.

https://www.figma.com/design/MSndQ5PKriB0SM3YeNxjf4/Ohne-Namen?node-id=0-1&p=f&t=55WNZzt3cS1ooSMW-0
